ELIXIR_BUILD_TYPE := OFFICIAL
ELIXIR_MAINTAINER := RahulPalXDA
TARGET_USES_AOSP_RECOVERY := true
TARGET_INCLUDE_STOCK_ACORE := false
TARGET_INCLUDE_LIVE_WALLPAPERS := false
TARGET_SUPPORTS_GOOGLE_RECORDER := false
